spring:
  cloud:
    gateway:
      routes:
        - id: r1
          uri: http://localhost:8082/
          predicates:
            - Path= /acheteurs/**
        - id: r2
          uri: http://localhost:8083/
          predicates:
            - Path= /produits/**
